# Generated by Django 6.0.3 on 2026-08-15 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_apikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bug', 'Bug — something is broken'), ('wish', 'Wish — feature request'), ('question', 'Question'), ('other', 'Other')], default='bug', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low — minor annoyance'), ('medium', 'Medium — workaround exists'), ('high', 'High — major impact'), ('blocker', 'Blocker — cannot continue')], default='medium', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='What happened, what you expected, and how to reproduce.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('page_url', models.URLField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewport_width', models.PositiveIntegerField(blank=True, null=True)),
                ('viewport_height', models.PositiveIntegerField(blank=True, null=True)),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True)),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True)),
                ('device_pixel_ratio', models.FloatField(blank=True, null=True)),
                ('browser_timezone', models.CharField(blank=True, max_length=100)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback/screenshots/%Y/%m/')),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('wont_fix', "Won't fix"), ('duplicate', 'Duplicate')], default='new', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugReportUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'New'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('wont_fix', "Won't fix"), ('duplicate', 'Duplicate')], max_length=16)),
                ('new_status', models.CharField(blank=True, choices=[('new', 'New'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('wont_fix', "Won't fix"), ('duplicate', 'Duplicate')], help_text='Leave blank to send a message without changing the status.', max_length=16)),
                ('message', models.TextField(blank=True, help_text='Sent to the reporter and shown on their reports page.')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback/attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_report_updates', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='feedback.bugreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bugreport',
            index=models.Index(fields=['status', '-created_at'], name='feedback_bu_status_38631c_idx'),
        ),
        migrations.AddIndex(
            model_name='bugreport',
            index=models.Index(fields=['kind', '-created_at'], name='feedback_bu_kind_14ae45_idx'),
        ),
    ]
